environment:
  matrix:
    - nodejs_version: '8'
version: "{build}"
build: off
matrix:
  fast_finish: true
install:
  - ps: $env:channel = "unstable"
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - choco install -y -i dokany --installargs INSTALLDEVFILES=1;
  - npm install
  - npm run dist
  - ps: $version = $env:APPVEYOR_REPO_TAG_NAME.substring(1)
  - ps: choco pack mount.balloon.nuspec --version=$version
  - ps: mv mount.balloon*.nupkg dist
test_script:
  - node --version
  - npm --version
  - SET PATH=C:\Program Files\Nodejs;%PATH%
artifacts:
  - path: dist\mount.balloon-win-x64.exe
    name: mount.balloon
  - path: dist\mount.balloon.$version.nupkg
    name: mount.balloon-choco
deploy:
  provider: GitHub
  auth_token:
    secure: jCxEiL6iLQGMyFkFptVvRACVSMy4HC9RzzLPzl1FCQsj9JNZObW+vnhYuP0tnfPy
  artifact: mount.balloon,mount.balloon-choco
  draft: false
  force_update: false
  on:
    appveyor_repo_tag: true
